In [2]:
#41. Generate marks for 50 students.
import numpy as np
arr = np.random.randint(20,101,50)
print("Marks of 50 Student:",arr)

Marks of 50 Student: [59 61 35 70 82 49 53 60 69 22 73 95 98 48 99 56 68 58 68 83 85 35 63 77
 59 97 79 87 95 90 42 59 28 80 29 50 23 38 85 52 72 21 22 25 21 95 93 40
 39 91]


In [11]:
#42. Calculate total, average, highest, lowest
marks = np.array( [59, 61 ,35, 70, 82, 49, 53, 60, 69, 22, 73, 95, 98, 48, 99, 56, 68, 58, 68, 83, 85, 35, 63, 77
, 59, 97, 79, 87, 95, 90, 42, 59, 28, 80 ,29, 50, 23, 38, 85, 52, 72, 21, 22, 25, 21, 95, 93, 40,
 39, 91])

total = np.sum(marks)
avg = np.average(marks)
maximum = np.max(marks)
minimum = np.min(marks)

print("Total:",total)
print("average",avg)
print("Highest:",maximum)
print("Lowest:",minimum)

Total: 3078
average 61.56
Highest: 99
Lowest: 21


In [12]:
##43. Count above 75, below 35, between 35-75.

marks=np.array( [59, 61 ,35, 70, 82, 49, 53, 60, 69, 22, 73, 95, 98, 48, 99, 56, 68, 58, 68, 83, 85, 35, 63, 77
, 59, 97, 79, 87, 95, 90, 42, 59, 28, 80 ,29, 50, 23, 38, 85, 52, 72, 21, 22, 25, 21, 95, 93, 40,
 39, 91])

count_above_75 = np.sum(marks > 75)
below_35 = np.sum(marks < 35)
between_35to75 = np.sum((marks >= 35) & (marks <= 75))
#print
print("above 75:",count_above_75)
print("below 35:",below_35)
print("between 35-75:",between_35to75)

above 75: 17
below 35: 8
between 35-75: 25


In [15]:
#44. Assign grades.
marks = np.array([59, 61 ,35, 70, 82, 49, 53, 60, 69, 22, 73, 95, 98, 48, 99, 56, 68, 58, 68, 83, 85, 35, 63, 77
, 59, 97, 79, 87, 95, 90, 42, 59, 28, 80 ,29, 50, 23, 38, 85, 52, 72, 21, 22, 25, 21, 95, 93, 40,
 39, 91])
grades = ([])
for i in marks:
    if i >= 90:
        grades.append("A")
    elif i >= 75:
        grades.append("B")
    elif i >= 60:
        grades.append("C")
    elif i >= 40:
        grades.append("D")
    else:
        grades.append("F")
        
print(grades)

['D', 'C', 'F', 'C', 'B', 'D', 'D', 'C', 'C', 'F', 'C', 'A', 'A', 'D', 'A', 'D', 'C', 'D', 'C', 'B', 'B', 'F', 'C', 'B', 'D', 'A', 'B', 'B', 'A', 'A', 'D', 'D', 'F', 'B', 'F', 'D', 'F', 'F', 'B', 'D', 'C', 'F', 'F', 'F', 'F', 'A', 'A', 'D', 'F', 'A']


In [21]:
##45. Display top 5 marks
marks = np.array([59, 61 ,35, 70, 82, 49, 53, 60, 69, 22, 73, 95, 98, 48, 99, 56, 68, 58, 68, 83, 85, 35, 63, 77
, 59, 97, 79, 87, 95, 90, 42, 59, 28, 80 ,29, 50, 23, 38, 85, 52, 72, 21, 22, 25, 21, 95, 93, 40,
 39, 91])
top = np.sort(marks)[-5:][::-1]
print("Top 5 makrs",top)


Top 5 makrs [99 98 97 95 95]


In [20]:

#Display bottom 5 marks.

marks = np.array([77 ,74, 85,54, 98, 96, 30, 51, 63, 73, 51, 75 ,66, 20 ,63, 20, 52, 97 ,25, 98 ,74 ,20 ])
bottom = np.sort(marks)
print(bottom[:6])

[20 20 20 25 30 51]


In [22]:
#Find median and standard deviation
marks = np.array([77 ,74, 85,54, 98, 96, 30, 51, 63, 73, 51, 75 ,66, 20 ,63, 20, 52, 97 ,25, 98 ,74 ,20 ])
print("median:",np.median(marks))
print("standard deviation:",np.std(marks))

median: 64.5
standard deviation: 25.59635821203884


In [24]:
#48. Create 5-subject marks matrix and calculate totals.
import numpy as np
arr = np.array([[89,67,87,90,67],
              [92,90,83,74,79],
              [82,84,92,91,89],
              [67,78,89,90,67],
              [90,78,78,90,67]])
print(np.sum(arr,axis=1))

[400 418 438 391 403]


In [25]:
#49. Find topper in each subject.
print(np.max(arr,axis=0))

[92 90 92 91 89]


In [27]:
arr = np.array([[89,67,87,90,67],
              [92,90,83,74,79],
              [82,84,92,91,89],
              [67,78,89,90,67],
              [90,78,78,90,67]])
#to find total
total = np.sum(arr,axis=1)
#to find average
average = np.average(arr,axis=1)
#to find percent
percentage = np.sum(arr,axis=1)/5

for i in range(len(total)):
    if i>= 90:
        grade = "A"
    elif i >= 75:
        grade = "B"
    elif i >= 60:
        grade = "C"
    elif i>= 40:
        grade = "D"
    else:
        grade = "F"

    print("Student", i + 1)
    print("Total      :", total[i])
    print("Average    :", average[i])
    print("Percentage :", percentage[i])
    print("Grade      :", grade)
    print()

Student 1
Total      : 400
Average    : 80.0
Percentage : 80.0
Grade      : B

Student 2
Total      : 418
Average    : 83.6
Percentage : 83.6
Grade      : B

Student 3
Total      : 438
Average    : 87.6
Percentage : 87.6
Grade      : B

Student 4
Total      : 391
Average    : 78.2
Percentage : 78.2
Grade      : B

Student 5
Total      : 403
Average    : 80.6
Percentage : 80.6
Grade      : B

